---
version: "2"
services:
    www:
        build: .
        ports:
            - "8081:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7.28
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: php_rds
            MYSQL_USER: PHILIP
            MYSQL_PASSWORD: Philip123
            MYSQL_ROOT_PASSWORD: philip
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8082:80
        environment:
            MYSQL_USER: philip
            MYSQL_PASSWORD: philip123
            MYSQL_ROOT_PASSWORD: philip
volumes:
    persistent:

